// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookinfo-srv/proto/bookinfo_micro/bookinfo.proto

package bookinfopb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetallRequest struct {
	// ID of user
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetallRequest) Reset()         { *m = GetallRequest{} }
func (m *GetallRequest) String() string { return proto.CompactTextString(m) }
func (*GetallRequest) ProtoMessage()    {}
func (*GetallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40171e36fb66b0d, []int{0}
}

func (m *GetallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetallRequest.Unmarshal(m, b)
}
func (m *GetallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetallRequest.Marshal(b, m, deterministic)
}
func (m *GetallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetallRequest.Merge(m, src)
}
func (m *GetallRequest) XXX_Size() int {
	return xxx_messageInfo_GetallRequest.Size(m)
}
func (m *GetallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetallRequest proto.InternalMessageInfo

func (m *GetallRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type GetallResponse struct {
	// Book info list
	Bookinfolist         []*BookInfo `protobuf:"bytes,1,rep,name=bookinfolist,proto3" json:"bookinfolist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetallResponse) Reset()         { *m = GetallResponse{} }
func (m *GetallResponse) String() string { return proto.CompactTextString(m) }
func (*GetallResponse) ProtoMessage()    {}
func (*GetallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40171e36fb66b0d, []int{1}
}

func (m *GetallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetallResponse.Unmarshal(m, b)
}
func (m *GetallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetallResponse.Marshal(b, m, deterministic)
}
func (m *GetallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetallResponse.Merge(m, src)
}
func (m *GetallResponse) XXX_Size() int {
	return xxx_messageInfo_GetallResponse.Size(m)
}
func (m *GetallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetallResponse proto.InternalMessageInfo

func (m *GetallResponse) GetBookinfolist() []*BookInfo {
	if m != nil {
		return m.Bookinfolist
	}
	return nil
}

type BookInfo struct {
	// Name of book
	BookName string `protobuf:"bytes,1,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	// Author
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// Chapters name
	ChaptersInfo         []*ChapterInfo `protobuf:"bytes,3,rep,name=chapters_info,json=chaptersInfo,proto3" json:"chapters_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BookInfo) Reset()         { *m = BookInfo{} }
func (m *BookInfo) String() string { return proto.CompactTextString(m) }
func (*BookInfo) ProtoMessage()    {}
func (*BookInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40171e36fb66b0d, []int{2}
}

func (m *BookInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookInfo.Unmarshal(m, b)
}
func (m *BookInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookInfo.Marshal(b, m, deterministic)
}
func (m *BookInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookInfo.Merge(m, src)
}
func (m *BookInfo) XXX_Size() int {
	return xxx_messageInfo_BookInfo.Size(m)
}
func (m *BookInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BookInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BookInfo proto.InternalMessageInfo

func (m *BookInfo) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

func (m *BookInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BookInfo) GetChaptersInfo() []*ChapterInfo {
	if m != nil {
		return m.ChaptersInfo
	}
	return nil
}

type ChapterInfo struct {
	// Chapter number
	ChapterNum int32 `protobuf:"zigzag32,1,opt,name=chapter_num,json=chapterNum,proto3" json:"chapter_num,omitempty"`
	// Chapter name
	ChapterName string `protobuf:"bytes,2,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	// Words cound
	WordsCount           int32    `protobuf:"zigzag32,3,opt,name=words_count,json=wordsCount,proto3" json:"words_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChapterInfo) Reset()         { *m = ChapterInfo{} }
func (m *ChapterInfo) String() string { return proto.CompactTextString(m) }
func (*ChapterInfo) ProtoMessage()    {}
func (*ChapterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40171e36fb66b0d, []int{3}
}

func (m *ChapterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterInfo.Unmarshal(m, b)
}
func (m *ChapterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterInfo.Marshal(b, m, deterministic)
}
func (m *ChapterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterInfo.Merge(m, src)
}
func (m *ChapterInfo) XXX_Size() int {
	return xxx_messageInfo_ChapterInfo.Size(m)
}
func (m *ChapterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterInfo proto.InternalMessageInfo

func (m *ChapterInfo) GetChapterNum() int32 {
	if m != nil {
		return m.ChapterNum
	}
	return 0
}

func (m *ChapterInfo) GetChapterName() string {
	if m != nil {
		return m.ChapterName
	}
	return ""
}

func (m *ChapterInfo) GetWordsCount() int32 {
	if m != nil {
		return m.WordsCount
	}
	return 0
}

type AddRequest struct {
	// Books information
	BooksInfo            []*BookInfo `protobuf:"bytes,1,rep,name=books_info,json=booksInfo,proto3" json:"books_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40171e36fb66b0d, []int{4}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetBooksInfo() []*BookInfo {
	if m != nil {
		return m.BooksInfo
	}
	return nil
}

type AddResponse struct {
	Field                []int32  `protobuf:"zigzag32,1,rep,packed,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c40171e36fb66b0d, []int{5}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetField() []int32 {
	if m != nil {
		return m.Field
	}
	return nil
}

func init() {
	proto.RegisterType((*GetallRequest)(nil), "bookinfo.GetallRequest")
	proto.RegisterType((*GetallResponse)(nil), "bookinfo.GetallResponse")
	proto.RegisterType((*BookInfo)(nil), "bookinfo.BookInfo")
	proto.RegisterType((*ChapterInfo)(nil), "bookinfo.ChapterInfo")
	proto.RegisterType((*AddRequest)(nil), "bookinfo.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "bookinfo.AddResponse")
}

func init() {
	proto.RegisterFile("bookinfo-srv/proto/bookinfo_micro/bookinfo.proto", fileDescriptor_c40171e36fb66b0d)
}

var fileDescriptor_c40171e36fb66b0d = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xbf, 0x7c, 0x1b, 0x09, 0x4c, 0xc1, 0x84, 0x0d, 0x68, 0x83, 0x07, 0xb0, 0x1e, 0xe4,
	0x22, 0x28, 0x1a, 0x0f, 0x26, 0xc6, 0x00, 0x07, 0xf5, 0xc2, 0xa1, 0x47, 0x2f, 0x4d, 0x61, 0xb7,
	0xa1, 0xa1, 0xed, 0xd6, 0xdd, 0xad, 0x1e, 0x3c, 0xf8, 0xaf, 0x9b, 0xfd, 0x45, 0x45, 0xe3, 0xf1,
	0xcd, 0x9b, 0x79, 0xf3, 0xc9, 0xec, 0xc2, 0xe5, 0x8a, 0xd2, 0x6d, 0x92, 0xc7, 0xf4, 0x82, 0xb3,
	0xb7, 0x49, 0xc1, 0xa8, 0xa0, 0x13, 0x5b, 0x0a, 0xb3, 0x64, 0xcd, 0x2a, 0x39, 0x56, 0x2e, 0x6a,
	0x58, 0xed, 0x9f, 0x43, 0xfb, 0x91, 0x88, 0x28, 0x4d, 0x03, 0xf2, 0x5a, 0x12, 0x2e, 0xd0, 0x11,
	0xd4, 0x4b, 0x4e, 0x58, 0x82, 0xbd, 0xda, 0xb0, 0x36, 0x6a, 0x06, 0x46, 0xf9, 0x4f, 0x70, 0x68,
	0x1b, 0x79, 0x41, 0x73, 0x4e, 0xd0, 0x2d, 0xb4, 0x6c, 0x4c, 0x9a, 0x70, 0xe1, 0xd5, 0x86, 0xce,
	0xc8, 0x9d, 0xa2, 0xf1, 0x6e, 0xd7, 0x9c, 0xd2, 0xed, 0x73, 0x1e, 0xd3, 0x60, 0xaf, 0xcf, 0xff,
	0x80, 0x86, 0x75, 0xd0, 0x09, 0x34, 0xa5, 0x17, 0xe6, 0x51, 0x46, 0xcc, 0x42, 0xc5, 0xb6, 0x8c,
	0x32, 0x22, 0x51, 0xa2, 0x52, 0x6c, 0x28, 0xf3, 0xfe, 0x6b, 0x14, 0xad, 0xd0, 0x1d, 0xb4, 0xd7,
	0x9b, 0xa8, 0x10, 0x84, 0xf1, 0x50, 0xa6, 0x7a, 0x8e, 0xda, 0xdc, 0xab, 0x36, 0x2f, 0xb4, 0xad,
	0x97, 0xdb, 0x5e, 0xa9, 0x7c, 0x06, 0xee, 0x37, 0x13, 0x0d, 0xc0, 0x35, 0x76, 0x98, 0x97, 0x99,
	0x22, 0xe8, 0x04, 0x60, 0x4a, 0xcb, 0x32, 0x43, 0xa7, 0xd0, 0xda, 0x35, 0x48, 0x46, 0x4d, 0x62,
	0x87, 0x14, 0xe6, 0x00, 0xdc, 0x77, 0xca, 0x30, 0x0f, 0xd7, 0xb4, 0xcc, 0x85, 0xe7, 0xe8, 0x0c,
	0x55, 0x5a, 0xc8, 0x8a, 0xff, 0x00, 0x30, 0xc3, 0xd8, 0x1e, 0xf8, 0x0a, 0x40, 0x72, 0x1a, 0xf4,
	0xbf, 0x8f, 0xa6, 0x0e, 0xa3, 0xa1, 0xcf, 0xc0, 0x55, 0x01, 0xe6, 0xf0, 0x5d, 0x38, 0x88, 0x13,
	0x92, 0x62, 0x35, 0xdc, 0x09, 0xb4, 0x98, 0x7e, 0xea, 0xb3, 0xca, 0x10, 0x74, 0x0f, 0x75, 0xfd,
	0x58, 0xe8, 0xb8, 0x4a, 0xde, 0x7b, 0xe7, 0xbe, 0xf7, 0xdb, 0xd0, 0xf1, 0xfe, 0x3f, 0x74, 0x03,
	0xce, 0x0c, 0x63, 0xd4, 0xad, 0x5a, 0x2a, 0xfe, 0x7e, 0xef, 0x47, 0xd5, 0x4e, 0xcd, 0x5b, 0x2f,
	0x60, 0x9d, 0x62, 0xb5, 0xaa, 0xab, 0x9f, 0x76, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0xde, 0x0e,
	0x8e, 0xd0, 0x9d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Bookinfo service

type BookinfoClient interface {
	// get book information
	Getall(ctx context.Context, in *GetallRequest, opts ...client.CallOption) (*GetallResponse, error)
	// add books information
	Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error)
}

type bookinfoClient struct {
	c           client.Client
	serviceName string
}

func NewBookinfoClient(serviceName string, c client.Client) BookinfoClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "bookinfo"
	}
	return &bookinfoClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *bookinfoClient) Getall(ctx context.Context, in *GetallRequest, opts ...client.CallOption) (*GetallResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Bookinfo.Getall", in)
	out := new(GetallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookinfoClient) Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Bookinfo.Add", in)
	out := new(AddResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bookinfo service

type BookinfoHandler interface {
	// get book information
	Getall(context.Context, *GetallRequest, *GetallResponse) error
	// add books information
	Add(context.Context, *AddRequest, *AddResponse) error
}

func RegisterBookinfoHandler(s server.Server, hdlr BookinfoHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Bookinfo{hdlr}, opts...))
}

type Bookinfo struct {
	BookinfoHandler
}

func (h *Bookinfo) Getall(ctx context.Context, in *GetallRequest, out *GetallResponse) error {
	return h.BookinfoHandler.Getall(ctx, in, out)
}

func (h *Bookinfo) Add(ctx context.Context, in *AddRequest, out *AddResponse) error {
	return h.BookinfoHandler.Add(ctx, in, out)
}
