// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookinfo-srv/proto/bookinfo/bookinfo.proto

package bookinfopb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetallRequest struct {
	// ID of user
	Userid               string   `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetallRequest) Reset()         { *m = GetallRequest{} }
func (m *GetallRequest) String() string { return proto.CompactTextString(m) }
func (*GetallRequest) ProtoMessage()    {}
func (*GetallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0db5783ead35437, []int{0}
}

func (m *GetallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetallRequest.Unmarshal(m, b)
}
func (m *GetallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetallRequest.Marshal(b, m, deterministic)
}
func (m *GetallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetallRequest.Merge(m, src)
}
func (m *GetallRequest) XXX_Size() int {
	return xxx_messageInfo_GetallRequest.Size(m)
}
func (m *GetallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetallRequest proto.InternalMessageInfo

func (m *GetallRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type GetallResponse struct {
	// Book info list
	Bookinfolist         []*BookInfo `protobuf:"bytes,1,rep,name=bookinfolist,proto3" json:"bookinfolist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetallResponse) Reset()         { *m = GetallResponse{} }
func (m *GetallResponse) String() string { return proto.CompactTextString(m) }
func (*GetallResponse) ProtoMessage()    {}
func (*GetallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0db5783ead35437, []int{1}
}

func (m *GetallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetallResponse.Unmarshal(m, b)
}
func (m *GetallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetallResponse.Marshal(b, m, deterministic)
}
func (m *GetallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetallResponse.Merge(m, src)
}
func (m *GetallResponse) XXX_Size() int {
	return xxx_messageInfo_GetallResponse.Size(m)
}
func (m *GetallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetallResponse proto.InternalMessageInfo

func (m *GetallResponse) GetBookinfolist() []*BookInfo {
	if m != nil {
		return m.Bookinfolist
	}
	return nil
}

type BookInfo struct {
	// Name of book
	BookName string `protobuf:"bytes,1,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	// Author
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// Chapters name
	ChaptersInfo         []*ChapterInfo `protobuf:"bytes,3,rep,name=chapters_info,json=chaptersInfo,proto3" json:"chapters_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BookInfo) Reset()         { *m = BookInfo{} }
func (m *BookInfo) String() string { return proto.CompactTextString(m) }
func (*BookInfo) ProtoMessage()    {}
func (*BookInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0db5783ead35437, []int{2}
}

func (m *BookInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookInfo.Unmarshal(m, b)
}
func (m *BookInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookInfo.Marshal(b, m, deterministic)
}
func (m *BookInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookInfo.Merge(m, src)
}
func (m *BookInfo) XXX_Size() int {
	return xxx_messageInfo_BookInfo.Size(m)
}
func (m *BookInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BookInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BookInfo proto.InternalMessageInfo

func (m *BookInfo) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

func (m *BookInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BookInfo) GetChaptersInfo() []*ChapterInfo {
	if m != nil {
		return m.ChaptersInfo
	}
	return nil
}

type ChapterInfo struct {
	// Chapter number
	ChapterNum int32 `protobuf:"zigzag32,1,opt,name=chapter_num,json=chapterNum,proto3" json:"chapter_num,omitempty"`
	// Chapter name
	ChapterName string `protobuf:"bytes,2,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	// Words cound
	WordsCount           int32    `protobuf:"zigzag32,3,opt,name=words_count,json=wordsCount,proto3" json:"words_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChapterInfo) Reset()         { *m = ChapterInfo{} }
func (m *ChapterInfo) String() string { return proto.CompactTextString(m) }
func (*ChapterInfo) ProtoMessage()    {}
func (*ChapterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0db5783ead35437, []int{3}
}

func (m *ChapterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterInfo.Unmarshal(m, b)
}
func (m *ChapterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterInfo.Marshal(b, m, deterministic)
}
func (m *ChapterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterInfo.Merge(m, src)
}
func (m *ChapterInfo) XXX_Size() int {
	return xxx_messageInfo_ChapterInfo.Size(m)
}
func (m *ChapterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterInfo proto.InternalMessageInfo

func (m *ChapterInfo) GetChapterNum() int32 {
	if m != nil {
		return m.ChapterNum
	}
	return 0
}

func (m *ChapterInfo) GetChapterName() string {
	if m != nil {
		return m.ChapterName
	}
	return ""
}

func (m *ChapterInfo) GetWordsCount() int32 {
	if m != nil {
		return m.WordsCount
	}
	return 0
}

type AddRequest struct {
	// Books information
	BooksInfo            []*BookInfo `protobuf:"bytes,1,rep,name=books_info,json=booksInfo,proto3" json:"books_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0db5783ead35437, []int{4}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetBooksInfo() []*BookInfo {
	if m != nil {
		return m.BooksInfo
	}
	return nil
}

type AddResponse struct {
	Field                []int32  `protobuf:"zigzag32,1,rep,packed,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0db5783ead35437, []int{5}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetField() []int32 {
	if m != nil {
		return m.Field
	}
	return nil
}

func init() {
	proto.RegisterType((*GetallRequest)(nil), "bookinfo.GetallRequest")
	proto.RegisterType((*GetallResponse)(nil), "bookinfo.GetallResponse")
	proto.RegisterType((*BookInfo)(nil), "bookinfo.BookInfo")
	proto.RegisterType((*ChapterInfo)(nil), "bookinfo.ChapterInfo")
	proto.RegisterType((*AddRequest)(nil), "bookinfo.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "bookinfo.AddResponse")
}

func init() {
	proto.RegisterFile("bookinfo-srv/proto/bookinfo/bookinfo.proto", fileDescriptor_a0db5783ead35437)
}

var fileDescriptor_a0db5783ead35437 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x95, 0x8d, 0xa8, 0x76, 0x27, 0x2d, 0x62, 0xad, 0x2d, 0x44, 0x5d, 0xa4, 0x5d, 0xcc,
	0x81, 0x55, 0x25, 0x1a, 0x51, 0x24, 0x0e, 0xbd, 0xa0, 0xb6, 0x07, 0x40, 0x42, 0x3d, 0xe4, 0x84,
	0xb8, 0x44, 0x6e, 0xed, 0xb6, 0x51, 0x13, 0x4f, 0x88, 0x1d, 0x38, 0x70, 0xe3, 0x15, 0x78, 0x13,
	0x5e, 0x85, 0x57, 0xe0, 0x41, 0x90, 0xed, 0xb8, 0xa1, 0x20, 0x6e, 0x99, 0x7f, 0x7e, 0xff, 0xf3,
	0x65, 0x6c, 0x18, 0xaf, 0x11, 0x0f, 0xb9, 0xdc, 0xe2, 0x73, 0x55, 0x7f, 0x4e, 0xaa, 0x1a, 0x35,
	0x26, 0x5e, 0x3a, 0x7e, 0x4c, 0xac, 0x4e, 0xce, 0x7d, 0x3d, 0x7a, 0xbc, 0x43, 0xdc, 0x15, 0x22,
	0x61, 0x55, 0x9e, 0x30, 0x29, 0x51, 0x33, 0x9d, 0xa3, 0x54, 0xce, 0x47, 0x9f, 0xc1, 0xe0, 0x8d,
	0xd0, 0xac, 0x28, 0x52, 0xf1, 0xa9, 0x11, 0x4a, 0x93, 0x87, 0xd0, 0x6b, 0x94, 0xa8, 0x73, 0x1e,
	0x07, 0xb7, 0xc1, 0xdd, 0x45, 0xda, 0x56, 0xf4, 0x2d, 0xdc, 0xf7, 0x46, 0x55, 0xa1, 0x54, 0x82,
	0xbc, 0x82, 0xbe, 0x1f, 0x52, 0xe4, 0x4a, 0xc7, 0xc1, 0x6d, 0x78, 0x17, 0x4d, 0xc9, 0xe4, 0x48,
	0xb2, 0x40, 0x3c, 0xbc, 0x93, 0x5b, 0x4c, 0x4f, 0x7c, 0xf4, 0x2b, 0x9c, 0xfb, 0x0e, 0xb9, 0x86,
	0x0b, 0xd3, 0xcb, 0x24, 0x2b, 0x45, 0x3b, 0xd0, 0x92, 0xaf, 0x58, 0x29, 0x0c, 0x0a, 0x6b, 0xf4,
	0x1e, 0xeb, 0xf8, 0xcc, 0xa1, 0xb8, 0x8a, 0xcc, 0x60, 0xb0, 0xd9, 0xb3, 0x4a, 0x8b, 0x5a, 0x65,
	0x26, 0x35, 0x0e, 0xed, 0xe4, 0x61, 0x37, 0x79, 0xe9, 0xda, 0x6e, 0xb8, 0xf7, 0x9a, 0x8a, 0xd6,
	0x10, 0xfd, 0xd1, 0x24, 0x37, 0x10, 0xb5, 0xed, 0x4c, 0x36, 0xa5, 0x25, 0xb8, 0x4c, 0xa1, 0x95,
	0x56, 0x4d, 0x49, 0x9e, 0x40, 0xff, 0x68, 0x30, 0x8c, 0x8e, 0xc4, 0x1f, 0xb2, 0x98, 0x37, 0x10,
	0x7d, 0xc1, 0x9a, 0xab, 0x6c, 0x83, 0x8d, 0xd4, 0x71, 0xe8, 0x32, 0xac, 0xb4, 0x34, 0x0a, 0x7d,
	0x0d, 0x30, 0xe7, 0xdc, 0x2f, 0xf8, 0x05, 0x80, 0xe1, 0x6c, 0xd1, 0xff, 0xbf, 0x34, 0xbb, 0x18,
	0x07, 0xfd, 0x14, 0x22, 0x1b, 0xd0, 0x2e, 0xfe, 0x0a, 0xee, 0x6d, 0x73, 0x51, 0x70, 0x7b, 0xf8,
	0x32, 0x75, 0xc5, 0xf4, 0x47, 0xe0, 0xf6, 0x6a, 0x52, 0xc8, 0x07, 0xe8, 0xb9, 0xdb, 0x22, 0x8f,
	0xba, 0xe8, 0x93, 0x8b, 0x1e, 0xc5, 0xff, 0x36, 0x5c, 0x3e, 0xbd, 0xfe, 0xf6, 0xf3, 0xd7, 0xf7,
	0xb3, 0x21, 0x7d, 0xd0, 0xbd, 0xae, 0x9d, 0x75, 0xcc, 0x82, 0x31, 0x79, 0x0f, 0xe1, 0x9c, 0x73,
	0x72, 0xd5, 0x9d, 0xee, 0xfe, 0x6d, 0x34, 0xfc, 0x4b, 0x6d, 0x03, 0x63, 0x1b, 0x48, 0xe8, 0xa0,
	0x0b, 0x64, 0x9c, 0xcf, 0x82, 0xf1, 0xa2, 0xff, 0x11, 0xbc, 0x54, 0xad, 0xd7, 0x3d, 0xfb, 0x26,
	0x5f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x82, 0xfa, 0x66, 0xe9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookinfoClient is the client API for Bookinfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookinfoClient interface {
	// get book information
	Getall(ctx context.Context, in *GetallRequest, opts ...grpc.CallOption) (*GetallResponse, error)
	// add books information
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type bookinfoClient struct {
	cc *grpc.ClientConn
}

func NewBookinfoClient(cc *grpc.ClientConn) BookinfoClient {
	return &bookinfoClient{cc}
}

func (c *bookinfoClient) Getall(ctx context.Context, in *GetallRequest, opts ...grpc.CallOption) (*GetallResponse, error) {
	out := new(GetallResponse)
	err := c.cc.Invoke(ctx, "/bookinfo.Bookinfo/Getall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookinfoClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/bookinfo.Bookinfo/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookinfoServer is the server API for Bookinfo service.
type BookinfoServer interface {
	// get book information
	Getall(context.Context, *GetallRequest) (*GetallResponse, error)
	// add books information
	Add(context.Context, *AddRequest) (*AddResponse, error)
}

// UnimplementedBookinfoServer can be embedded to have forward compatible implementations.
type UnimplementedBookinfoServer struct {
}

func (*UnimplementedBookinfoServer) Getall(ctx context.Context, req *GetallRequest) (*GetallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Getall not implemented")
}
func (*UnimplementedBookinfoServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterBookinfoServer(s *grpc.Server, srv BookinfoServer) {
	s.RegisterService(&_Bookinfo_serviceDesc, srv)
}

func _Bookinfo_Getall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookinfoServer).Getall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookinfo.Bookinfo/Getall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookinfoServer).Getall(ctx, req.(*GetallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookinfo_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookinfoServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookinfo.Bookinfo/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookinfoServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bookinfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bookinfo.Bookinfo",
	HandlerType: (*BookinfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Getall",
			Handler:    _Bookinfo_Getall_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Bookinfo_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bookinfo-srv/proto/bookinfo/bookinfo.proto",
}
